AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal Test Stack for OpenSearch Role Mapping Lambda - Fixed Race Condition'

Parameters:
  ExistingOpenSearchDomainEndpoint:
    Type: String
    Default: 'search-condenast-aos-domain-3hmon7me6ct3p5e46snecxe6f4.us-east-1.es.amazonaws.com'
    Description: Existing OpenSearch domain endpoint (without https://)
  
  ExistingOpenSearchDomainName:
    Type: String
    Default: 'condenast-aos-domain'
    Description: Name of the existing OpenSearch domain
  
  AccountId:
    Type: String
    Default: '943143228843'
    Description: AWS Account ID

Resources:
  # Lambda Execution Role - Created FIRST
  OpenSearchRoleMappingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'test-opensearch-role-mapper-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AssumeAdminRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub 'arn:aws:iam::${AccountId}:role/test-opensearch-admin-role'

  # OpenSearch Admin Role - Created SECOND (after LambdaRole exists)
  OpenSearchAdminRole:
    Type: AWS::IAM::Role
    DependsOn: OpenSearchRoleMappingLambdaRole  # ✅ FIX: Wait for Lambda role to exist
    Properties:
      RoleName: 'test-opensearch-admin-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AccountId}:root'
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              # ✅ Now safe to use !GetAtt because DependsOn ensures role exists
              AWS: !GetAtt OpenSearchRoleMappingLambdaRole.Arn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OpenSearchAdminAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpGet
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpPatch
                  - es:ESHttpDelete
                  - es:ESHttpHead
                  - es:DescribeDomain
                Resource:
                  - !Sub 'arn:aws:es:${AWS::Region}:${AccountId}:domain/${ExistingOpenSearchDomainName}'
                  - !Sub 'arn:aws:es:${AWS::Region}:${AccountId}:domain/${ExistingOpenSearchDomainName}/*'

  # Dummy Role to Test Mapping
  TestRole1:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'test-opensearch-user-role-1'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  TestRole2:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'test-opensearch-user-role-2'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  # Lambda Function - Maps roles to OpenSearch
  OpenSearchRoleMappingLambda:
    Type: AWS::Lambda::Function
    DependsOn: OpenSearchAdminRole  # Ensure admin role exists before Lambda is created
    Properties:
      FunctionName: 'test-opensearch-role-mapper'
      Runtime: python3.11
      Handler: index.lambda_handler
      Timeout: 60
      MemorySize: 256
      Role: !GetAtt OpenSearchRoleMappingLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib3
          from botocore.auth import SigV4Auth
          from botocore.awsrequest import AWSRequest
          
          http = urllib3.PoolManager()
          sts = boto3.client('sts')
          
          def send_response(event, context, status, data=None):
              """Send response to CloudFormation"""
              response_body = {
                  'Status': status,
                  'PhysicalResourceId': event.get('PhysicalResourceId', 'OpenSearchRoleMapping'),
                  'StackId': event['StackId'],
                  'RequestId': event['RequestId'],
                  'LogicalResourceId': event['LogicalResourceId'],
                  'Data': data or {}
              }
              
              try:
                  http.request(
                      'PUT',
                      event['ResponseURL'],
                      body=json.dumps(response_body),
                      headers={'Content-Type': 'application/json'}
                  )
              except Exception as e:
                  print(f"Failed to send response: {str(e)}")
          
          def lambda_handler(event, context):
              """Maps IAM roles to OpenSearch internal roles"""
              print(f"Event: {json.dumps(event)}")
              
              try:
                  if event['RequestType'] == 'Delete':
                      print("Delete request - no action needed")
                      send_response(event, context, 'SUCCESS')
                      return
                  
                  domain_endpoint = event['ResourceProperties']['DomainEndpoint'].replace('https://', '').replace('http://', '')
                  admin_role_arn = event['ResourceProperties']['AdminRoleArn']
                  role_mappings = event['ResourceProperties']['RoleMappings']
                  
                  print(f"Domain: {domain_endpoint}")
                  print(f"Admin Role: {admin_role_arn}")
                  print(f"Mappings: {json.dumps(role_mappings, indent=2)}")
                  
                  print("🔑 Assuming OpenSearch Admin Role...")
                  assumed_role = sts.assume_role(
                      RoleArn=admin_role_arn,
                      RoleSessionName='cfn-opensearch-mapper',
                      DurationSeconds=900
                  )
                  
                  admin_creds = assumed_role['Credentials']
                  print("✅ Admin role assumed successfully")
                  
                  class TempCredentials:
                      def __init__(self, access_key, secret_key, token):
                          self.access_key = access_key
                          self.secret_key = secret_key
                          self.token = token
                  
                  credentials = TempCredentials(
                      admin_creds['AccessKeyId'],
                      admin_creds['SecretAccessKey'],
                      admin_creds['SessionToken']
                  )
                  
                  region = 'us-east-1'
                  service = 'es'
                  results = {}
                  
                  for opensearch_role, backend_roles in role_mappings.items():
                      url = f"https://{domain_endpoint}/_plugins/_security/api/rolesmapping/{opensearch_role}"
                      
                      get_request = AWSRequest(
                          method='GET',
                          url=url,
                          headers={'Content-Type': 'application/json'}
                      )
                      SigV4Auth(credentials, service, region).add_auth(get_request)
                      
                      get_response = http.request(
                          method=get_request.method,
                          url=get_request.url,
                          headers=dict(get_request.headers)
                      )
                      
                      existing_mapping = {}
                      if get_response.status == 200:
                          response_json = json.loads(get_response.data.decode('utf-8'))
                          existing_mapping = response_json.get(opensearch_role, {})
                      
                      body = {
                          "backend_roles": backend_roles,
                          "hosts": existing_mapping.get("hosts", []),
                          "users": existing_mapping.get("users", [])
                      }
                      
                      print(f"📝 Mapping {opensearch_role} with {len(backend_roles)} roles")
                      
                      request = AWSRequest(
                          method='PUT',
                          url=url,
                          data=json.dumps(body),
                          headers={'Content-Type': 'application/json'}
                      )
                      SigV4Auth(credentials, service, region).add_auth(request)
                      
                      response = http.request(
                          method=request.method,
                          url=request.url,
                          body=request.body,
                          headers=dict(request.headers)
                      )
                      
                      response_data = response.data.decode('utf-8')
                      print(f"Response: {response.status} - {response_data}")
                      
                      if response.status in [200, 201]:
                          results[opensearch_role] = 'SUCCESS'
                      else:
                          results[opensearch_role] = f'FAILED: {response_data}'
                  
                  failures = [role for role, result in results.items() if 'FAILED' in result]
                  
                  if failures:
                      print(f"❌ Failed to map: {failures}")
                      send_response(event, context, 'FAILED', {'Results': results})
                  else:
                      print(f"✅ All mappings successful")
                      send_response(event, context, 'SUCCESS', {'Results': results})
                  
              except Exception as e:
                  print(f"❌ Error: {str(e)}")
                  import traceback
                  traceback.print_exc()
                  send_response(event, context, 'FAILED', {'Error': str(e)})

  # Custom Resource - Triggers Lambda to map roles
  OpenSearchRoleMappingCustomResource:
    Type: Custom::OpenSearchRoleMapping
    DependsOn:
      - OpenSearchRoleMappingLambda
      - OpenSearchAdminRole
      - TestRole1
      - TestRole2
    Properties:
      ServiceToken: !GetAtt OpenSearchRoleMappingLambda.Arn
      DomainEndpoint: !Ref ExistingOpenSearchDomainEndpoint
      AdminRoleArn: !GetAtt OpenSearchAdminRole.Arn
      RoleMappings:
        all_access:
          - !GetAtt TestRole1.Arn
          - !GetAtt TestRole2.Arn
          - !GetAtt OpenSearchRoleMappingLambdaRole.Arn
          - !Sub 'arn:aws:iam::${AccountId}:root'

Outputs:
  OpenSearchRoleMappingLambdaArn:
    Description: OpenSearch Role Mapping Lambda Function ARN
    Value: !GetAtt OpenSearchRoleMappingLambda.Arn
  
  OpenSearchAdminRoleArn:
    Description: OpenSearch Admin Role ARN (Master User)
    Value: !GetAtt OpenSearchAdminRole.Arn
  
  TestRole1Arn:
    Description: Test Role 1 ARN
    Value: !GetAtt TestRole1.Arn
  
  TestRole2Arn:
    Description: Test Role 2 ARN
    Value: !GetAtt TestRole2.Arn
  
  CustomResourceStatus:
    Description: Custom Resource Status
    Value: !Ref OpenSearchRoleMappingCustomResource
