AWSTemplateFormatVersion: '2010-09-09'
Description: Private S3 + CloudFront (OAC) for frontend + CloudFront in front of ALB API

Parameters:
  FrontendBucketName:
    Type: String
    Default: condenast-fe
    Description: Name of existing S3 bucket that stores frontend (e.g. condenast-fe)

  AlbDnsName:
    Type: String
    Description: DNS name of the ALB (e.g. condenast-alb-1886974946.us-east-1.elb.amazonaws.com)

Resources:
  ############################
  # Frontend (S3 + OAC CFN)
  ############################
  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-frontend-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        IPV6Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6   # AWS "CachingOptimized"
        Origins:
          - Id: FrontendS3Origin
            DomainName: !Sub '${FrontendBucketName}.s3.${AWS::Region}.${AWS::URLSuffix}'
            OriginAccessControlId: !GetAtt FrontendOAC.Id
            OriginPath: ""                    # or /FE if your site is under a prefix
            S3OriginConfig:
              OriginAccessIdentity: ""        # must be empty when using OAC

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontReadFromThisDistribution
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${FrontendBucketName}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}'

  ############################
  # API CloudFront (fronts ALB)
  ############################
  ApiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: ApiOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
        Origins:
          - Id: ApiOrigin
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 8000
              HTTPSPort: 443

Outputs:
  FrontendCloudFrontDomainName:
    Description: CloudFront URL for the frontend
    Value: !GetAtt FrontendDistribution.DomainName

  ApiCloudFrontDomainName:
    Description: CloudFront URL for the API (use as backendUrl)
    Value: !GetAtt ApiDistribution.DomainName
